name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List Files
        run: ls -R

      - name: Extract Mod Info
        id: get_version
        run: |
          mod_version=$(jq -r '.Version' HorizontalUi/manifest.json)
          echo "mod_version=$mod_version" >> $GITHUB_ENV

      - name: Generate Changes
        id: changelog
        run: |
          git fetch --tags
          last_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -z "$last_tag" ]; then
            log=$(git log --pretty=format:'- %s')
          else
            log=$(git log $last_tag..HEAD --pretty=format:'- %s')
          fi
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$log" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.mod_version }}
          body: ${{ env.CHANGELOG }}
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}